### PR TITLE
Fix bug in guess output validator

### PR DESCRIPTION
**Pull request by RagnarGrootKoerkamp**
Currently it's possible to have the following interaction with the adaptive interactor:
```
400
higher
700
higher
1
higher
600
lower
```

We ran into this because we increased the number of allowed queries to `1000` for the BAPC testsession and somebody submitted a program guessing `37*i%1000+1` on the `i`th try.

### CODE REVIEW

**Comment by pehrsoderman** [comment]
@RagnarGrootKoerkamp Can you add an example solution triggering this bug to the problem package as well?

**Comment by RagnarGrootKoerkamp** [comment]
@pehrsoderman done, but it's not so effective: the solution needs 1000 queries to be AC, but the limit is only 10 here so it will be WA anyways.

**Comment by pehrsoderman** [comment]
@RagnarGrootKoerkamp Can you add something that, for example, makes the solution crash out if the bug is present? And a comment, to make it a little less 😲 if you don't know what is there for?

Sorry for the nitpicking. I should have been more clear to start with.

**Comment by RagnarGrootKoerkamp** [comment]
@pehrsoderman done now! The submission should get WA, but currently gets an RTE.

**Comment by pehrsoderman** [comment]
@RagnarGrootKoerkamp Great, thanks!

**Pull request merged**
