### PR TITLE
Cleanup `problem2{pdf,html}` and use f-strings in `verifyproblem`

### PR DESCRIPTION
**Pull request by JoelNiemela**
For `problem2{pdf,html}`:
- Changes the default value for `--language` to `None` instead of `''`, and changes code expecting to see `''`. This is partially to improve the `--help` message, which used to read `--language [...] (default: )`. It now reads `(default: None)`
- Removes the option `--title`, as this was never used.

For `verifyproblem`:
- Replaces uses of the `%` operator with f-strings.

### CODE REVIEW

**Comment by JoelNiemela** [comment]
> There is a bare except with no specified exception type in template.py, maybe clean that up too while you're at it.

I considered it, but I can't find any documentation that lists which exceptions can be thrown by `"file object".write`.

**Comment by simonlindholm** [comment]
`except Exception` is better than `except:` except if the catch block does cleanup and then rethrows, since `except:` catches things like thread/program cancellation as well as error exceptions.

In this case it looks like `line % data` is the part that is expected to throw, rather than `.write()`, and that probably only throws a single kind of exception.

**Comment by Tagl** [comment]
IOError and OSError are two at least, maybe there are more. My idea was
simply to have it Exception though instead of catching everything.

**Comment by Tagl** [comment]
Oh it seems that IOError and OSError are equivalent in Python 3.

**Comment by Tagl** [comment]
> In this case it looks like `line % data` is the part that is expected to throw, rather than `.write()`, and that probably only throws a single kind of exception.

And that is TypeError, So I think this could be changed to catch TypeError and OSError and everything else that could come up is probably a sign of some greater issue.

**Comment by JoelNiemela** [comment]
> In this case it looks like line % data is the part that is expected to throw, rather than .write(), and that probably only throws a single kind of exception.

Ah, you're right. I tested this and it looks like the exception that is handled is `KeyError`.

I won't catch `OSError` or `TypeError` since this would only be caused by `write` failing, or `data` not being a dictionary, neither of which are handled in the `catch` body.

**Review by Tagl — APPROVED** [review]

**Review by pehrsoderman — APPROVED** [review]

**Pull request merged**
