### PR TITLE
Add scala as supported language

### PR DESCRIPTION
**Pull request by Tarrasch**
For now just run Scala in interpreted mode. Future work could be to use
scalac. I didn't do it in this patch as I'm not familiar enough with the
typical scalac flags.

### CODE REVIEW

**Comment by austrin** [comment]
@Tarrasch I'm not sure how useful this is on its own, since there is no Scala support in Kattis.  This would let you use Scala for validators though, is that what you want?

**Comment by Tarrasch** [comment]
I didn't consider that.

But yes. My use case is that I wrote my own reference solution in Scala. And I would like for problemstools to be able to verify my solution against the provided `.ans` files. :)

**Comment by Tarrasch** [comment]
Can this be either merged, closed or reviewed again please?

**Comment by austrin** [comment]
@Tarrasch sorry for lack of response, I thought I had already responded.  I'll close this for now, it is not that generally useful since Kattis does not support Scala.

**Comment by Tarrasch** [comment]
Better late than never.

Though I don't understand why this is not merged as it makes perfect sense to have in my work-flow. But if you think my use-case is rare, I trust you to have made the right decision to close this. :)

**Pull request closed without merging**
